# =======================================================
# CYD SOLAR MONITOR - GROW BOX DESIGN V2
# =======================================================
substitutions:
  name: "cyd-solar-display"
  friendly_name: "CYD Solar Display"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# WiFi & API
wifi:
  ap:
    ssid: "CYD-Solar-Setup"
    password: ""
captive_portal:
web_server:
  port: 80

api:
  services:
    - service: update_display
      variables:
        solar: float
        grid: float
        house: float
        bat_w: float
        bat_soc: float
        val_yield: float
        val_yield_month: float
        val_yield_year: float
        val_yield_total: float
        grid_in: float
        grid_out: float
        page_num: int
        c1_n: string
        c1_v: string
        c2_n: string
        c2_v: string
        c3_n: string
        c3_v: string
        c4_n: string
        c4_v: string
      then:
        - lambda: |-
            id(solar_w).publish_state(solar);
            id(grid_w).publish_state(grid);
            id(house_w).publish_state(house);
            id(battery_w).publish_state(bat_w);
            id(battery_soc).publish_state(bat_soc);
            id(yield_today).publish_state(val_yield);
            id(yield_month).publish_state(val_yield_month);
            id(yield_year).publish_state(val_yield_year);
            id(yield_total).publish_state(val_yield_total);
            id(grid_import).publish_state(grid_in);
            id(grid_export).publish_state(grid_out);
            id(current_page).publish_state(page_num);
            id(custom1_n).publish_state(c1_n);
            id(custom1_v).publish_state(c1_v);
            id(custom2_n).publish_state(c2_n);
            id(custom2_v).publish_state(c2_v);
            id(custom3_n).publish_state(c3_n);
            id(custom3_v).publish_state(c3_v);
            id(custom4_n).publish_state(c4_n);
            id(custom4_v).publish_state(c4_v);

ota:
  - platform: esphome

logger:
  level: DEBUG

# Hardware Setup (CYD)
spi:
  clk_pin: 14
  mosi_pin: 13
  miso_pin: 12

output:
  - platform: ledc
    pin: 21
    id: backlight_pwm
light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

# Colors (OpenKairo Cyberpunk Aesthetic)
color:
  - id: color_bg
    red: 0%
    green: 0%
    blue: 0%
  - id: color_text
    red: 100%
    green: 100%
    blue: 100%
  - id: color_panel
    red: 6%
    green: 6%
    blue: 8% 
  - id: color_solar
    red: 98%
    green: 93%
    blue: 3%
  - id: color_house
    red: 0%
    green: 95%
    blue: 100%
  - id: color_grid_in
    red: 100%
    green: 0%
    blue: 23%
  - id: color_grid_out
    red: 0%
    green: 100%
    blue: 45%
  - id: color_bat
    red: 69%
    green: 15%
    blue: 100%

# Fonts
font:
  - file: "gfonts://Roboto"
    id: font_title
    size: 14
  - file: "gfonts://Roboto"
    id: font_value
    size: 24
  - file: "gfonts://Roboto"
    id: font_label
    size: 12

# Sensors
sensor:
  - platform: template
    name: "Solar Power"
    id: solar_w
    unit_of_measurement: "W"
  - platform: template
    name: "Grid Power"
    id: grid_w
    unit_of_measurement: "W"
  - platform: template
    name: "House Power"
    id: house_w
    unit_of_measurement: "W"
  - platform: template
    name: "Battery SoC"
    id: battery_soc
    unit_of_measurement: "%"
  - platform: template
    name: "Battery Power"
    id: battery_w
    unit_of_measurement: "W"
  - platform: template
    name: "Yield Today"
    id: yield_today
    unit_of_measurement: "kWh"
    accuracy_decimals: 1
  - platform: template
    name: "Yield Month"
    id: yield_month
    unit_of_measurement: "kWh"
    accuracy_decimals: 1
  - platform: template
    name: "Yield Year"
    id: yield_year
    unit_of_measurement: "kWh"
    accuracy_decimals: 1
  - platform: template
    name: "Yield Total"
    id: yield_total
    unit_of_measurement: "kWh"
    accuracy_decimals: 1
  - platform: template
    name: "Grid Import"
    id: grid_import
    unit_of_measurement: "kWh"
    accuracy_decimals: 1
  - platform: template
    name: "Grid Export"
    id: grid_export
    unit_of_measurement: "kWh"
    accuracy_decimals: 1

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "CYD IP Address"
      id: wifi_ip
  - platform: template
    name: "Custom 1 Name"
    id: custom1_n
  - platform: template
    name: "Custom 1 Value"
    id: custom1_v
  - platform: template
    name: "Custom 2 Name"
    id: custom2_n
  - platform: template
    name: "Custom 2 Value"
    id: custom2_v
  - platform: template
    name: "Custom 3 Name"
    id: custom3_n
  - platform: template
    name: "Custom 3 Value"
    id: custom3_v
  - platform: template
    name: "Custom 4 Name"
    id: custom4_n
  - platform: template
    name: "Custom 4 Value"
    id: custom4_v

number:
  - platform: template
    name: "Current Page"
    id: current_page
    min_value: 1
    max_value: 2
    step: 1
    optimistic: true

# Display Logic (Grow Box Design)
display:
  - platform: ili9xxx
    model: ILI9341
    id: cyd_display
    cs_pin: 15
    dc_pin: 2
    invert_colors: false
    color_order: BGR
    # Palette optimization from the working Grow Box example
    color_palette: 8BIT
    rotation: 90
    lambda: |-
      static const char *TAG = "display";
      
      // Background
      it.fill(id(color_bg));

      // Check if data available
      if (std::isnan(id(solar_w).state)) {
        it.print(160, 90, id(font_title), id(color_text), TextAlign::TOP_CENTER, "Warten auf Daten...");
        it.printf(160, 140, id(font_label), id(color_text), TextAlign::TOP_CENTER, "IP: %s", id(wifi_ip).state.c_str());
        return;
      }

      int page = (int)id(current_page).state;

      // HEADER
      it.filled_rectangle(0, 0, 320, 32, id(color_panel));
      it.print(10, 6, id(font_title), id(color_solar), TextAlign::TOP_LEFT, "Solar");
      it.print(310, 6, id(font_title), id(color_text), TextAlign::TOP_RIGHT, "Live Daten");
      it.line(0, 32, 320, 32, id(color_text));

      if (page == 1) {
        // 1. SOLAR (Top Center)
        it.rectangle(100, 42, 120, 55, id(color_panel)); 
        it.filled_rectangle(100, 42, 3, 10, id(color_solar)); // Cyberpunk Accent
        it.print(160, 50, id(font_label), id(color_solar), TextAlign::TOP_CENTER, "SOLAR");
        it.printf(160, 67, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.0f W", id(solar_w).state);
        
        // 2. BATTERIE (Middle Left)
        it.rectangle(15, 107, 110, 45, id(color_panel));
        it.filled_rectangle(15, 107, 3, 10, id(color_bat)); // Cyberpunk Accent
        it.print(70, 113, id(font_label), id(color_bat), TextAlign::TOP_CENTER, "BATTERIE");
        it.printf(70, 128, id(font_title), id(color_text), TextAlign::TOP_CENTER, "%.0f%% / %.0fW", id(battery_soc).state, id(battery_w).state);
        
        // 3. HAUS (Middle Right)
        it.rectangle(195, 107, 110, 45, id(color_panel));
        it.filled_rectangle(195, 107, 3, 10, id(color_house)); // Cyberpunk Accent
        it.print(250, 113, id(font_label), id(color_house), TextAlign::TOP_CENTER, "HAUSVERBRAUCH");
        it.printf(250, 128, id(font_title), id(color_text), TextAlign::TOP_CENTER, "%.0f W", id(house_w).state);
        
        // 4. NETZ (Bottom Center)
        auto g_val = id(grid_w).state;
        auto g_color = (g_val <= 0) ? id(color_grid_out) : id(color_grid_in);
        const char* g_label = (g_val <= 0) ? "EINSPEISUNG" : "NETZBEZUG";
        it.rectangle(100, 162, 120, 55, id(color_panel));
        it.filled_rectangle(100, 162, 3, 10, g_color); // Cyberpunk Accent
        it.print(160, 170, id(font_label), g_color, TextAlign::TOP_CENTER, g_label);
        it.printf(160, 187, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.0f W", abs(g_val));
      } else if (page == 2) {
        // PAGE 2 (STATISTICS) - OPENKAIRO STYLE
        
        // 1. ERTRAG TAG
        it.rectangle(15, 50, 140, 65, id(color_panel));
        it.filled_rectangle(15, 50, 4, 15, id(color_solar));
        it.print(85, 60, id(font_label), id(color_solar), TextAlign::TOP_CENTER, "ERTRAG TAG");
        it.printf(85, 82, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.1f", id(yield_today).state);
        
        // 2. ERTRAG MONAT
        it.rectangle(165, 50, 140, 65, id(color_panel));
        it.filled_rectangle(165, 50, 4, 15, id(color_solar));
        it.print(235, 60, id(font_label), id(color_solar), TextAlign::TOP_CENTER, "ERTRAG MONAT");
        it.printf(235, 82, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.1f", id(yield_month).state);

        // 3. ERTRAG JAHR
        it.rectangle(15, 125, 140, 65, id(color_panel));
        it.filled_rectangle(15, 125, 4, 15, id(color_solar));
        it.print(85, 135, id(font_label), id(color_solar), TextAlign::TOP_CENTER, "ERTRAG JAHR");
        it.printf(85, 157, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.1f", id(yield_year).state);

        // 4. GESAMTERTRAG
        it.rectangle(165, 125, 140, 65, id(color_panel));
        it.filled_rectangle(165, 125, 4, 15, id(color_solar));
        it.print(235, 135, id(font_label), id(color_solar), TextAlign::TOP_CENTER, "GESAMTERTRAG");
        it.printf(235, 157, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.1f", id(yield_total).state); 
      } else {
        // PAGE 3 (CUSTOM OPENKAIRO SENSORS)
        
        // C1
        it.rectangle(15, 50, 140, 65, id(color_panel));
        it.filled_rectangle(15, 50, 4, 15, id(color_house)); 
        it.print(85, 60, id(font_label), id(color_house), TextAlign::TOP_CENTER, id(custom1_n).state.c_str());
        it.printf(85, 82, id(font_title), id(color_text), TextAlign::TOP_CENTER, "%s", id(custom1_v).state.c_str());
        
        // C2
        it.rectangle(165, 50, 140, 65, id(color_panel));
        it.filled_rectangle(165, 50, 4, 15, id(color_grid_out));
        it.print(235, 60, id(font_label), id(color_grid_out), TextAlign::TOP_CENTER, id(custom2_n).state.c_str());
        it.printf(235, 82, id(font_title), id(color_text), TextAlign::TOP_CENTER, "%s", id(custom2_v).state.c_str());

        // C3
        it.rectangle(15, 125, 140, 65, id(color_panel));
        it.filled_rectangle(15, 125, 4, 15, id(color_bat));
        it.print(85, 135, id(font_label), id(color_bat), TextAlign::TOP_CENTER, id(custom3_n).state.c_str());
        it.printf(85, 157, id(font_title), id(color_text), TextAlign::TOP_CENTER, "%s", id(custom3_v).state.c_str());

        // C4
        it.rectangle(165, 125, 140, 65, id(color_panel));
        it.filled_rectangle(165, 125, 4, 15, id(color_grid_in));
        it.print(235, 135, id(font_label), id(color_grid_in), TextAlign::TOP_CENTER, id(custom4_n).state.c_str());
        it.printf(235, 157, id(font_title), id(color_text), TextAlign::TOP_CENTER, "%s", id(custom4_v).state.c_str()); 
      }

      // FOOTER
      it.filled_rectangle(0, 222, 320, 18, id(color_panel));
      it.line(0, 222, 320, 222, id(color_text));
      
      it.printf(160, 225, id(font_label), id(color_house), TextAlign::TOP_CENTER, "SEITE %d / 3", page);

# Touchscreen Setup
touchscreen:
  - platform: xpt2046
    cs_pin: 33
    interrupt_pin: 36
    threshold: 400
    calibration:
      x_min: 380
      x_max: 3800
      y_min: 300
      y_max: 3800
    transform:
      mirror_x: true
      mirror_y: false
      swap_xy: true
