# =======================================================
# CYD SOLAR MONITOR - GROW BOX DESIGN V2
# =======================================================
substitutions:
  name: "cyd-solar-display"
  friendly_name: "CYD Solar Display"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# WiFi & API
wifi:
  ap:
    ssid: "CYD-Solar-Setup"
    password: ""
captive_portal:
web_server:
  port: 80

api:
  services:
    - service: update_display
      variables:
        solar: float
        grid: float
        house: float
        bat_w: float
        bat_soc: float
        yield: float
        grid_in: float
        grid_out: float
        page_num: int
      then:
        - lambda: |-
            id(solar_w).publish_state(solar);
            id(grid_w).publish_state(grid);
            id(house_w).publish_state(house);
            id(battery_w).publish_state(bat_w);
            id(battery_soc).publish_state(bat_soc);
            id(yield_today).publish_state(yield);
            id(grid_import).publish_state(grid_in);
            id(grid_export).publish_state(grid_out);
            id(current_page).publish_state(page_num);

ota:
  - platform: esphome

logger:
  level: DEBUG

# Hardware Setup (CYD)
spi:
  clk_pin: 14
  mosi_pin: 13
  miso_pin: 12

output:
  - platform: ledc
    pin: 21
    id: backlight_pwm
light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

# Colors (Based on Grow Box Dashboard)
color:
  - id: color_bg
    red: 0%
    green: 0%
    blue: 0%
  - id: color_text
    red: 100%
    green: 100%
    blue: 100%
  - id: color_panel
    red: 10%
    green: 10%
    blue: 10% 
  - id: color_solar
    red: 100%
    green: 85%
    blue: 20%
  - id: color_house
    red: 20%
    green: 70%
    blue: 100%
  - id: color_grid_in
    red: 90%
    green: 20%
    blue: 20%
  - id: color_grid_out
    red: 30%
    green: 90%
    blue: 30%
  - id: color_bat
    red: 65%
    green: 55%
    blue: 100%

# Fonts
font:
  - file: "gfonts://Roboto"
    id: font_title
    size: 20
  - file: "gfonts://Roboto"
    id: font_value
    size: 28
  - file: "gfonts://Roboto"
    id: font_label
    size: 12

# Sensors
sensor:
  - platform: template
    name: "Solar Power"
    id: solar_w
    unit_of_measurement: "W"
  - platform: template
    name: "Grid Power"
    id: grid_w
    unit_of_measurement: "W"
  - platform: template
    name: "House Power"
    id: house_w
    unit_of_measurement: "W"
  - platform: template
    name: "Battery SoC"
    id: battery_soc
    unit_of_measurement: "%"
  - platform: template
    name: "Battery Power"
    id: battery_w
    unit_of_measurement: "W"
  - platform: template
    name: "Yield Today"
    id: yield_today
    unit_of_measurement: "kWh"
  - platform: template
    name: "Grid Import"
    id: grid_import
    unit_of_measurement: "kWh"
  - platform: template
    name: "Grid Export"
    id: grid_export
    unit_of_measurement: "kWh"
    accuracy_decimals: 1

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "CYD IP Address"
      id: wifi_ip

number:
  - platform: template
    name: "Current Page"
    id: current_page
    min_value: 1
    max_value: 2
    step: 1
    optimistic: true

# Display Logic (Grow Box Design)
display:
  - platform: ili9xxx
    model: ILI9341
    id: cyd_display
    cs_pin: 15
    dc_pin: 2
    invert_colors: true
    color_order: BGR
    # Palette optimization from the working Grow Box example
    color_palette: 8BIT
    rotation: 90
    lambda: |-
      static const char *TAG = "display";
      
      // Background
      it.fill(id(color_bg));

      // Check if data available
      if (std::isnan(id(solar_w).state)) {
        it.print(160, 90, id(font_title), id(color_text), TextAlign::TOP_CENTER, "Warten auf Daten...");
        it.printf(160, 140, id(font_label), id(color_text), TextAlign::TOP_CENTER, "IP: %s", id(wifi_ip).state.c_str());
        return;
      }

      int page = (int)id(current_page).state;

      // HEADER
      it.filled_rectangle(0, 0, 320, 32, id(color_panel));
      it.print(10, 6, id(font_title), id(color_solar), TextAlign::TOP_LEFT, "Solar");
      it.print(310, 6, id(font_title), id(color_text), TextAlign::TOP_RIGHT, "Live Daten");
      it.line(0, 32, 320, 32, id(color_text));

      if (page == 1) {
        // 1. SOLAR (Top Center)
        it.filled_rectangle(100, 42, 120, 55, id(color_panel));
        it.print(160, 50, id(font_label), id(color_solar), TextAlign::TOP_CENTER, "SOLAR");
        it.printf(160, 67, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.0f W", id(solar_w).state);
        
        // 2. BATTERIE (Middle Left)
        it.filled_rectangle(15, 107, 110, 45, id(color_panel));
        it.print(70, 113, id(font_label), id(color_bat), TextAlign::TOP_CENTER, "BATTERIE");
        it.printf(70, 128, id(font_title), id(color_text), TextAlign::TOP_CENTER, "%.0f%% / %.0fW", id(battery_soc).state, id(battery_w).state);
        
        // 3. HAUS (Middle Right)
        it.filled_rectangle(195, 107, 110, 45, id(color_panel));
        it.print(250, 113, id(font_label), id(color_house), TextAlign::TOP_CENTER, "HAUSVERBRAUCH");
        it.printf(250, 128, id(font_title), id(color_text), TextAlign::TOP_CENTER, "%.0f W", id(house_w).state);
        
        // 4. NETZ (Bottom Center)
        auto g_val = id(grid_w).state;
        auto g_color = (g_val <= 0) ? id(color_grid_out) : id(color_grid_in);
        const char* g_label = (g_val <= 0) ? "EINSPEISUNG" : "NETZBEZUG";
        it.filled_rectangle(100, 162, 120, 55, id(color_panel));
        it.print(160, 170, id(font_label), g_color, TextAlign::TOP_CENTER, g_label);
        it.printf(160, 187, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.0f W", abs(g_val));
      } else {
        // PAGE 2 (STATISTICS)
        // 1. ERTRAG
        it.filled_rectangle(15, 50, 140, 65, id(color_panel));
        it.print(85, 60, id(font_label), id(color_solar), TextAlign::TOP_CENTER, "ERTRAG HEUTE");
        it.printf(85, 82, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.1f", id(yield_today).state);
        
        // 2. NETZBEZUG
        it.filled_rectangle(165, 50, 140, 65, id(color_panel));
        it.print(235, 60, id(font_label), id(color_grid_in), TextAlign::TOP_CENTER, "NETZBEZUG");
        it.printf(235, 82, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.1f", id(grid_import).state);

        // 3. EINSPEISUNG
        it.filled_rectangle(15, 125, 140, 65, id(color_panel));
        it.print(85, 135, id(font_label), id(color_grid_out), TextAlign::TOP_CENTER, "EINSPEISUNG");
        it.printf(85, 157, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.1f", id(grid_export).state);

        // 4. AUTARKIE (SIMULATED OR CALCULATION)
        it.filled_rectangle(165, 125, 140, 65, id(color_panel));
        it.print(235, 135, id(font_label), id(color_house), TextAlign::TOP_CENTER, "AUTARKIE");
        it.printf(235, 157, id(font_value), id(color_text), TextAlign::TOP_CENTER, "94 %%"); 
      }

      // FOOTER
      it.filled_rectangle(0, 222, 320, 18, id(color_panel));
      it.line(0, 222, 320, 222, id(color_text));
      
      if (page == 1) {
          it.print(160, 225, id(font_label), id(color_solar), TextAlign::TOP_CENTER, "Seite 1 / 2");
      } else {
          it.print(160, 225, id(font_label), id(color_solar), TextAlign::TOP_CENTER, "Seite 2 / 2");
      }

# Touchscreen Setup
touchscreen:
  - platform: xpt2046
    cs_pin: 33
    interrupt_pin: 36
    threshold: 400
    calibration:
      x_min: 380
      x_max: 3800
      y_min: 300
      y_max: 3800
    transform:
      mirror_x: true
      mirror_y: false
      swap_xy: true
