esphome:
  name: cyd-solar-display
  friendly_name: CYD Solar Display

esp32:
  board: esp32dev
  framework:
    type: arduino

# WiFi Konfiguration mit Captive Portal (macht eine AP auf, wenn kein WLAN gefunden wird)
wifi:
  # Falls du schon Daten hast, kannst du sie hier eintragen:
  # ssid: "DEINE_SSID"
  # password: "DEIN_PASSWORT"
  
  ap:
    ssid: "CYD-Solar-Setup"
    password: "" # Kein Passwort für den Setup-AP

captive_portal:

# Aktiviert die Weboberfläche
web_server:
  port: 80

# Native API mit Dienst-Definition für HA
api:
  services:
    - service: update_display
      variables:
        solar: float
        grid: float
        house: float
        bat_w: float
        bat_soc: float
        yield: float
        grid_in: float
        grid_out: float
        page_num: int
      then:
        - lambda: |-
            id(solar_w).publish_state(solar);
            id(grid_w).publish_state(grid);
            id(house_w).publish_state(house);
            id(battery_w).publish_state(bat_w);
            id(battery_soc).publish_state(bat_soc);
            id(yield_today).publish_state(yield);
            id(grid_import).publish_state(grid_in);
            id(grid_export).publish_state(grid_out);
            id(current_page).publish_state(page_num);

ota:
  - platform: esphome
    password: ""

logger:
  level: DEBUG
  baud_rate: 115200

# RGB LED & Backlight
output:
  - platform: ledc
    pin: 4
    inverted: true
    id: led_red
  - platform: ledc
    pin: 16
    inverted: true
    id: led_green
  - platform: ledc
    pin: 17
    inverted: true
    id: led_blue
  - platform: ledc
    pin: 21
    id: backlight_pwm

light:
  - platform: rgb
    name: "Status LED"
    red: led_red
    green: led_green
    blue: led_blue
    id: status_led
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

# --- DISPLAY SETUP (Cheap Yellow Display 2.8") ---
spi:
  clk_pin: 14
  mosi_pin: 13
  miso_pin: 12

display:
  - platform: ili9xxx
    id: cyd_display
    model: ILI9341
    cs_pin: 15
    dc_pin: 2
    invert_colors: true
    color_order: BGR
    rotation: 90
    lambda: |-
      static const char *TAG = "display";
      
      // Colors (Modern Palette)
      auto color_bg = Color(10, 15, 30);
      auto color_solar = Color(253, 216, 53); // Solar Yellow
      auto color_house = Color(56, 189, 248); // Tech Blue
      auto color_grid_in = Color(239, 83, 80); // Grid Import (Red)
      auto color_grid_out = Color(74, 222, 128); // Grid Export (Green)
      auto color_bat = Color(167, 139, 250); // Battery Purple
      
      it.fill(color_bg);

      // --- CHECK IF DATA IS READY ---
      if (std::isnan(id(solar_w).state)) {
        it.print(160, 100, id(font_medium), Color::WHITE, TextAlign::TOP_CENTER, "Warten auf Daten...");
        it.printf(160, 140, id(font_small), Color(150, 150, 150), TextAlign::TOP_CENTER, "IP: %s", id(wifi_ip).state.c_str());
        return;
      }

      // Top Bar
      it.rectangle(0, 0, 320, 30, Color(30, 41, 59));
      it.print(160, 5, id(font_small), Color::WHITE, TextAlign::TOP_CENTER, "CYD SOLAR MONITOR");
      
      if (id(current_page).state == 1) {
        // --- PAGE 1: LIVE POWER FLOW ---
        
        // Solar Box
        it.printf(10, 45, id(font_medium), color_solar, "Erzeugung:");
        it.printf(160, 40, id(font_large), color_solar, TextAlign::TOP_CENTER, "%.0f W", id(solar_w).state);
        
        // House Box
        it.printf(10, 95, id(font_medium), color_house, "Verbrauch:");
        it.printf(160, 90, id(font_large), color_house, TextAlign::TOP_CENTER, "%.0f W", id(house_w).state);
        
        // Grid Box
        auto g_val = id(grid_w).state;
        auto g_color = (g_val <= 0) ? color_grid_out : color_grid_in;
        const char* g_label = (g_val <= 0) ? "Einspeisung:" : "Netzbezug:";
        it.printf(10, 145, id(font_medium), g_color, g_label);
        it.printf(160, 140, id(font_large), g_color, TextAlign::TOP_CENTER, "%.0f W", abs(g_val));
        
        // Battery Box
        it.printf(10, 195, id(font_medium), color_bat, "Batterie:");
        it.printf(160, 190, id(font_large), Color::WHITE, TextAlign::TOP_CENTER, "%.0f%%", id(battery_soc).state);
        it.printf(250, 203, id(font_small), color_bat, "(%.0f W)", id(battery_w).state);

      } else {
        // --- PAGE 2: DAILY STATISTICS ---
        it.print(160, 40, id(font_medium), Color::WHITE, TextAlign::TOP_CENTER, "Tagesstatistik");
        it.line(40, 65, 280, 65, Color(100, 100, 100));
        
        it.printf(20, 80, id(font_medium), color_solar, "Heute Ertrag:");
        it.printf(300, 80, id(font_medium), Color::WHITE, TextAlign::TOP_RIGHT, "%.1f kWh", id(yield_today).state);
        
        it.printf(20, 120, id(font_medium), color_grid_in, "Netz-Bezug:");
        it.printf(300, 120, id(font_medium), Color::WHITE, TextAlign::TOP_RIGHT, "%.1f kWh", id(grid_import).state);
        
        it.printf(20, 160, id(font_medium), color_grid_out, "Einspeisung:");
        it.printf(300, 160, id(font_medium), Color::WHITE, TextAlign::TOP_RIGHT, "%.1f kWh", id(grid_export).state);
        
        // Footer hint
        it.print(160, 210, id(font_small), Color(150, 150, 150), TextAlign::TOP_CENTER, "Werte werden alle 5s aktualisiert");
      }

      // Page indicators
      for(int i=0; i<2; i++) {
        it.filled_circle(310, 110 + (i*20), 4, (id(current_page).state == i+1) ? Color::WHITE : Color(60, 60, 60));
      }

      // Display IP Address in Footer
      it.printf(5, 225, id(font_tiny), Color(100, 100, 100), TextAlign::BOTTOM_LEFT, "IP: %s", id(wifi_ip).state.c_str());
      it.printf(315, 225, id(font_tiny), Color(100, 100, 100), TextAlign::BOTTOM_RIGHT, "v1.1.2");

# --- DATEN-HALTER (Werden von der HA Integration befüllt) ---
# Wir nutzen Template-Sensoren, die Werte halten
sensor:
  - platform: template
    name: "Solar Power"
    id: solar_w
    unit_of_measurement: "W"
    accuracy_decimals: 0

  - platform: template
    name: "Grid Power"
    id: grid_w
    unit_of_measurement: "W"
    accuracy_decimals: 0

  - platform: template
    name: "House Power"
    id: house_w
    unit_of_measurement: "W"
    accuracy_decimals: 0

  - platform: template
    name: "Battery SoC"
    id: battery_soc
    unit_of_measurement: "%"
    accuracy_decimals: 0

  - platform: template
    name: "Battery Power"
    id: battery_w
    unit_of_measurement: "W"
    accuracy_decimals: 0

  - platform: template
    name: "Yield Today"
    id: yield_today
    unit_of_measurement: "kWh"
    accuracy_decimals: 1

  - platform: template
    name: "Grid Import"
    id: grid_import
    unit_of_measurement: "kWh"
    accuracy_decimals: 1

  - platform: template
    name: "Grid Export"
    id: grid_export
    unit_of_measurement: "kWh"
    accuracy_decimals: 1

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "CYD IP Address"
      id: wifi_ip

# Aktuelle Seite
number:
  - platform: template
    name: "Current Page"
    id: current_page
    min_value: 1
    max_value: 2
    step: 1
    initial_value: 1
    optimistic: true

# --- ENDPOINT FÜR DIE INTEGRATION ---
# Diese Automatisierung empfängt das JSON der HA Integration
http_request:
  useragent: esphome/cyd

# Um native JSON POSTs von meiner Integration zu empfangen, 
# nutzen wir den web_server und definieren Lambdas für die API.
# Hinweis: Die einfachste Methode in ESPHome ist, die Sensoren 
# über Home Assistant Dienste zu aktualisieren oder meine Integration
# nutzt die REST API von ESPHome.

# --- SCHRIFTARTEN ---
font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 14
  - file: "gfonts://Roboto"
    id: font_medium
    size: 22
  - file: "gfonts://Roboto"
    id: font_large
    size: 32
  - file: "gfonts://Roboto"
    id: font_tiny
    size: 10

