# =======================================================
# CYD SOLAR MONITOR - GROW BOX DESIGN V2
# =======================================================
substitutions:
  name: "cyd-solar-display"
  friendly_name: "CYD Solar Display"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# WiFi & API
wifi:
  ap:
    ssid: "CYD-Solar-Setup"
    password: ""
captive_portal:
web_server:
  port: 80

api:
  services:
    - service: update_display
      variables:
        solar: float
        grid: float
        house: float
        bat_w: float
        bat_soc: float
        yield: float
        grid_in: float
        grid_out: float
        page_num: int
      then:
        - lambda: |-
            id(solar_w).publish_state(solar);
            id(grid_w).publish_state(grid);
            id(house_w).publish_state(house);
            id(battery_w).publish_state(bat_w);
            id(battery_soc).publish_state(bat_soc);
            id(yield_today).publish_state(yield);
            id(grid_import).publish_state(grid_in);
            id(grid_export).publish_state(grid_out);
            id(current_page).publish_state(page_num);

ota:
  - platform: esphome

logger:
  level: DEBUG

# Hardware Setup (CYD)
spi:
  clk_pin: 14
  mosi_pin: 13
  miso_pin: 12

output:
  - platform: ledc
    pin: 21
    id: backlight_pwm
light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: ALWAYS_ON

# Colors (Based on Grow Box Dashboard)
color:
  - id: color_bg
    red: 0%
    green: 0%
    blue: 0%
  - id: color_text
    red: 100%
    green: 100%
    blue: 100%
  - id: color_panel
    red: 10%
    green: 10%
    blue: 10% 
  - id: color_solar
    red: 100%
    green: 85%
    blue: 20%
  - id: color_house
    red: 20%
    green: 70%
    blue: 100%
  - id: color_grid_in
    red: 90%
    green: 20%
    blue: 20%
  - id: color_grid_out
    red: 30%
    green: 90%
    blue: 30%
  - id: color_bat
    red: 65%
    green: 55%
    blue: 100%

# Fonts
font:
  - file: "gfonts://Roboto"
    id: font_title
    size: 20
  - file: "gfonts://Roboto"
    id: font_value
    size: 28
  - file: "gfonts://Roboto"
    id: font_label
    size: 12

# Sensors
sensor:
  - platform: template
    name: "Solar Power"
    id: solar_w
    unit_of_measurement: "W"
  - platform: template
    name: "Grid Power"
    id: grid_w
    unit_of_measurement: "W"
  - platform: template
    name: "House Power"
    id: house_w
    unit_of_measurement: "W"
  - platform: template
    name: "Battery SoC"
    id: battery_soc
    unit_of_measurement: "%"
  - platform: template
    name: "Battery Power"
    id: battery_w
    unit_of_measurement: "W"
  - platform: template
    name: "Yield Today"
    id: yield_today
    unit_of_measurement: "kWh"
  - platform: template
    name: "Grid Import"
    id: grid_import
    unit_of_measurement: "kWh"
  - platform: template
    name: "Grid Export"
    id: grid_export
    unit_of_measurement: "kWh"
    accuracy_decimals: 1

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "CYD IP Address"
      id: wifi_ip

number:
  - platform: template
    name: "Current Page"
    id: current_page
    min_value: 1
    max_value: 2
    step: 1
    optimistic: true

# Display Logic (Grow Box Design)
display:
  - platform: ili9xxx
    model: ILI9341
    id: cyd_display
    cs_pin: 15
    dc_pin: 2
    invert_colors: true
    color_order: BGR
    # Palette optimization from the working Grow Box example
    color_palette: 8BIT
    rotation: 90
    lambda: |-
      static const char *TAG = "display";
      
      // Background
      it.fill(id(color_bg));

      // Check if data available
      if (std::isnan(id(solar_w).state)) {
        it.print(160, 70, id(font_title), id(color_text), TextAlign::TOP_CENTER, "Warten auf Daten...");
        it.printf(160, 110, id(font_label), id(color_text), TextAlign::TOP_CENTER, "IP: %s", id(wifi_ip).state.c_str());
        it.print(160, 140, id(font_label), id(color_solar), TextAlign::TOP_CENTER, "Bitte diese IP in der");
        it.print(160, 155, id(font_label), id(color_solar), TextAlign::TOP_CENTER, "HA Integration eingeben.");
        return;
      }

      // HEADER
      it.filled_rectangle(0, 0, 320, 32, id(color_panel));
      it.print(10, 6, id(font_title), id(color_solar), TextAlign::TOP_LEFT, "Solar");
      it.print(310, 6, id(font_title), id(color_text), TextAlign::TOP_RIGHT, "Live Daten");
      it.line(0, 32, 320, 32, id(color_text));
      
      // GRID DIMENSIONS
      int w = 145;
      int h = 75;
      
      // 1. SOLAR (Top Left)
      it.filled_rectangle(10, 42, w, h, id(color_panel));
      it.print(20, 50, id(font_label), id(color_solar), TextAlign::TOP_LEFT, "ERZEUGUNG");
      it.printf(82, 72, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.0f W", id(solar_w).state);
      
      // 2. HOUSE (Top Right)
      it.filled_rectangle(165, 42, w, h, id(color_panel));
      it.print(175, 50, id(font_label), id(color_house), TextAlign::TOP_LEFT, "VERBRAUCH");
      it.printf(237, 72, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.0f W", id(house_w).state);
      
      // 3. GRID (Bottom Left)
      auto g_val = id(grid_w).state;
      auto g_color = (g_val <= 0) ? id(color_grid_out) : id(color_grid_in);
      const char* g_label = (g_val <= 0) ? "EINSPEISUNG" : "NETZBEZUG";
      it.filled_rectangle(10, 125, w, h, id(color_panel));
      it.print(20, 133, id(font_label), g_color, TextAlign::TOP_LEFT, g_label);
      it.printf(82, 155, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.0f W", abs(g_val));
      
      // 4. BATTERY (Bottom Right)
      it.filled_rectangle(165, 125, w, h, id(color_panel));
      it.print(175, 133, id(font_label), id(color_bat), TextAlign::TOP_LEFT, "BATTERIE");
      it.printf(237, 145, id(font_value), id(color_text), TextAlign::TOP_CENTER, "%.0f%%", id(battery_soc).state);
      it.printf(237, 178, id(font_label), id(color_bat), TextAlign::TOP_CENTER, "(%.0f W)", id(battery_w).state);
      
      // FOOTER
      it.filled_rectangle(0, 208, 320, 32, id(color_panel));
      it.line(0, 208, 320, 208, id(color_text));
      
      it.printf(10, 215, id(font_label), id(color_solar), TextAlign::TOP_LEFT, "Ertrag: %.1fkWh", id(yield_today).state);
      it.printf(310, 215, id(font_label), id(color_text), TextAlign::TOP_RIGHT, "v2.0.0");

# Touchscreen Setup
touchscreen:
  - platform: xpt2046
    cs_pin: 33
    interrupt_pin: 36
    threshold: 400
    calibration:
      x_min: 380
      x_max: 3800
      y_min: 300
      y_max: 3800
    transform:
      mirror_x: true
      mirror_y: false
      swap_xy: true
